<?php
// application/layouts/scripts/layout.phtml

print $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title><?php print $this->headTitle; ?></title>
  <?php print $this->headLink()->prependStylesheet('/css/global.css'); ?>
  <?php print $this->headScript()->appendFile('/js/positionUserInfo.js'); // ->appendFile('/js/center.js'); ?>
</head>
<body>
	<div id="center">
		<div id="header">
		    <div id="header-logo">
		        <img src="/img/cacert4.png" border="0" alt="CACert Logo" width="100px" height="30px">
		    </div>
		    <div id="header-navigation">
		    	<?php print $this->topNav(); ?>
		    </div>
		</div>

		<div id="left-navigation">
			<?php print $this->leftNav(); ?>
		</div>
		<div id="content">
			<?php print $this->layout()->content; ?>
		</div>
	</div>
	<? print $this->userInfo(); ?>
</body>
</html>