<?php
/**
 * @author Michael Tänzer
 */
?>

<h1><?php print I18n::_('Add Assurance Points to your Account') ?></h1>

<h2><?php print I18n::_('Get Points by Automated Assurance') ?></h2>
<p><?php print I18n::_('Assign the points by doing an automated assurance '.
    'which looks just like a normal assurance done by a real person.') ?></p>
<p><?php print I18n::_('If you enter more than 35 points they will be split '.
    'into multiple assurances. You can do zero point assurances.') ?></p>
<?php print $this->assurance_form ?>
