<?php
/**
 * @author Michael Tänzer
 */
?>

<h1><?php print I18n::_('Points added successfully')?></h1>

<p><?php print I18n::_('The following assurances were added to your account:')?></p>

<table>
	<thead>
		<tr><th>#</th><th><?php print I18n::_('Number of points')?></th></tr>
	</thead>
	<tbody>
		<?php foreach ($this->assurancesDone as $i => $points) {
		    printf('<tr><td> %1$d </td><td> %2$d </td></tr>', $i, $points);
		}?>
	</tbody>
</table>
