<?php
/**
 * @author Michael Tänzer
 */
?>

<h1><?php echo I18n::_('Manage your Test-Account')?></h1>

<p><?php echo I18n::_('Here you can manage various aspects of your account on '.
    'the test server')?></p>

<h2><?php echo I18n::_('Get Points by Automated Assurance') ?></h2>
<p><?php echo I18n::_('Assign points by doing an automated assurance '.
    'which looks just like a normal assurance done by a real person.') ?></p>
